site_name: 'backstage-alpha-docs'

nav:
  - Home: 'index.md'

plugins:
  - techdocs-core
  - build_plantuml:
      render: "server"
      bin_path: "/usr/local/bin/plantuml"
      server: "http://www.plantuml.com/plantuml"
      disable_ssl_certificate_validation: true
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      theme_enabled: false

markdown_extensions:
  - markdown_inline_mermaid
